name: Push main branch to Dev Server
run-name: ${{ github.actor }} ran this
on: workflow_dispatch
jobs:
  run-ssh-script:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        script: |
          cd /home
          ./update.sh
